### ISSUE TITLE
Addon does not work with filtered decks

### ISSUE THREAD

**Issue by FluorineTinOxide** [lovac42/SlackersDelight#2]
Trying to use the addon to review filtered decks and the defer button does not appear. Is this a planned feature down the line?

**Comment by lovac42** [comment]
I haven't tested it fully, but it shouldn't be a problem sending from filter to filter. I only blocked it in case someone tries to defer from the slacker deck to the slacker deck. For now, you can bury the card in the filter deck and it'll be moved back to the original deck.

**Comment by lovac42** [comment]
just updated

**Comment by FluorineTinOxide** [comment]
Thanks! Just tried it and works as intended. The "defer" button doesn't show up with filtered decks but using the shortcut key "_" is more than enough and gets the job done. Once again, thanks!

**Comment by lovac42** [comment]
Thanks for reporting, I'll fixed it now.
