### ISSUE TITLE
Filtered deck is always created without my permission

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/SlackersDelight#3]
After the last update, the Addon always creates the filtered deck "**Slackers Postponed Delights**" even though I do not click the button.

Previously, this deck was only created by clicking the button.

**Comment by lovac42** [comment]
Yeah I didn't think that mattered since you already have this addon installed.
fix: https://github.com/lovac42/SlackersDelight/releases/tag/v0.1.2

**Comment by cjdduarte** [comment]
Tanks
