### ISSUE TITLE
Pop Up Dictionary incompatibility?

### ISSUE THREAD

**Issue by ghost** [lovac42/SlackersDelight#4]
Not sure what exactly the conflict is, If i disable slacker's delight, popupdictionary works. 

Would love to be able to use both together.

**Comment by lovac42** [comment]
I'm not sure how PUD works, but testing just the two addons, it seems to work with no issues. The two addons does not patch the same part of anki, so there should not be a conflict. Perhapse describe what "conflict" you are experiencing. The dict was popping up during review, much to my dismay.

**Comment by lovac42** [comment]
@alih1029 The recent update should have resolved this issue, try updating the addon by going to addon manager and click on the update button.
